In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read the data companies.json
# and create a dataframe
df = pd.read_json("posts_axel.json")
df.head()

,scraped_at,name,summary,description,website,industry,headquarters,size,type,founded,specialties,linkedin_url,affiliated_pages,similar_pages,followers,posts
0,2023-04-25 13:41:43,Collins Community Credit Union,Aspire. Ignite. Achieve.,What started in 1940 by ten Collins Radio Empl...,https://www.linkedin.com/redir/redirect?url=ht...,Banking,"Cedar Rapids, Iowa",201-500 employees,Nonprofit,1940,"Banking, Finance, Teamwork, Collaboration, Gro...",https://www.linkedin.com/company/collins-commu...,[],[https://www.linkedin.com/company/greenstatecu...,1474,"[{'time': '3mo', 'text': 'Collins Community Cr..."
1,2023-04-25 13:41:43,Headline Solar,Fastest Growing Solar Company in the Midwest a...,Headline Solar is the fastest-growing solar co...,https://www.linkedin.com/redir/redirect?url=ht...,Renewable Energy Semiconductor Manufacturing,"Hoffman Estates, Illinois",11-50 employees,Privately Held,2018,"Solar Energy, Marketing, Sales, Solar, and Ren...",https://www.linkedin.com/company/headlinesolar,[],[https://www.linkedin.com/company/tron-solar?t...,1219,"[{'time': '3w', 'text': 'In August 2022, the I..."
2,2023-04-25 13:41:44,Tephra Labs,Technology for large-scale human coordination,Governments and companies have failed to move ...,https://www.linkedin.com/redir/redirect?url=ht...,Software Development,"New York City, New York",2-10 employees,Privately Held,2022,,https://www.linkedin.com/company/tephralabs,[],[https://www.linkedin.com/company/protocollabs...,287,"[{'time': '9mo', 'text': 'We are so excited to..."
3,2023-04-25 13:41:44,Oxford Properties Group,,"We are a leading global real estate investor, ...",https://www.linkedin.com/redir/redirect?url=ht...,Real Estate,"Toronto, Ontario","1,001-5,000 employees",Privately Held,,"Real Estate, Development, Investment, Property...",https://ca.linkedin.com/company/oxford-propert...,[https://ca.linkedin.com/company/omers?trk=aff...,[https://ca.linkedin.com/company/cadillac-fair...,74185,"[{'time': '21h', 'text': 'Pushing the boundari..."
4,2023-04-25 13:41:44,"Daikin America, Inc",New Possibilities for Everyday Living,Daikin has been a world leader in the developm...,https://www.linkedin.com/redir/redirect?url=ht...,Chemical Manufacturing,"Orangeburg, NY",201-500 employees,Public Company,1991,,https://www.linkedin.com/company/daikin-america,[],[https://www.linkedin.com/company/daikin-appli...,13015,"[{'time': '5d', 'text': 'https://lnkd.in/eTbkD..."

In [3]:
print(f"Step 1, {len(df)} rows")
df = df.replace("", np.nan)
df = df.replace(-1, np.nan)
df = df[df["name"] != "Confidential"]


print(f"Step 2, {len(df)} rows")
df = df[df["posts"].apply(len) > 0]

print(f"Step 3, {len(df)} rows")
df = df[~df["followers"].isna()]

print(f"Final, {len(df)} rows")

df.isna().sum()

Step 1, 2794 rows
Step 2, 2791 rows
Step 3, 2368 rows
Final, 2358 rows

scraped_at            0
name                  0
summary             317
description           0
website              17
industry              0
headquarters         45
size                  0
type                  6
founded             430
specialties         546
linkedin_url          0
affiliated_pages      0
similar_pages         0
followers             0
posts                 0
dtype: int64

In [4]:
# Explode the posts column
df = df.explode("posts")

In [5]:
# Convert the posts column into multiple columns
# The posts column is a dictionary
# We want to convert it into multiple columns
df = pd.concat([df.drop(["posts"], axis=1), df["posts"].apply(pd.Series)], axis=1)

In [6]:
df = df[["time", "text", "likes", "comments", "content_type"]]

In [11]:
df["content_type"].unique()

array(['image', 'text', 'reshare', 'external_video', 'video', 'link',
       'carousel', 'live_stream'], dtype=object)

In [7]:
# save df to csv
df.to_csv("cleaned_posts.csv", index=False)

In [ ]:
from langdetect import detect

def detect_language(text):
    try:
        return detect(text)
    except:
        return None

df['language'] = df['text'].apply(detect_language)

df = df[df['language'] == 'en']

df = df.drop(columns=['language'])
df